# Generated by Django 5.1.15 on 2026-03-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_created_43fcd6_idx',
            old_name='auditlog_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_resourc_933c45_idx',
            old_name='auditlog_resource_created_idx',
        ),
    ]
