# Generated by Django 5.1.15 on 2026-03-25 11:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_address_employee_avatar_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_name', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('WINDOWS', 'Windows'), ('MACOS', 'macOS'), ('LINUX', 'Linux')], max_length=20)),
                ('agent_version', models.CharField(default='1.0.0', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('SUSPENDED', 'Suspended'), ('UNINSTALLED', 'Uninstalled')], default='PENDING', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('machine_id', models.CharField(max_length=200, unique=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_devices', to='employees.employee')),
            ],
            options={
                'db_table': 'agent_devices',
                'ordering': ['-last_heartbeat'],
            },
        ),
        migrations.CreateModel(
            name='AgentCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('SUSPEND', 'Suspend'), ('RESUME', 'Resume'), ('KILL_SWITCH', 'Kill Switch'), ('UNINSTALL', 'Uninstall'), ('WIPE_DATA', 'Wipe Data'), ('FORCE_SYNC', 'Force Sync'), ('FORCE_UPDATE', 'Force Update'), ('UPDATE_CONFIG', 'Update Config')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='agent.agentdevice')),
            ],
            options={
                'db_table': 'agent_commands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('idle_seconds', models.PositiveIntegerField(default=0)),
                ('keystrokes', models.PositiveIntegerField(default=0)),
                ('mouse_clicks', models.PositiveIntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='agent.agentdevice')),
            ],
            options={
                'db_table': 'agent_activity_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AppUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(max_length=300)),
                ('window_title', models.CharField(blank=True, max_length=500)),
                ('total_seconds', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('PRODUCTIVE', 'Productive'), ('NEUTRAL', 'Neutral'), ('UNPRODUCTIVE', 'Unproductive'), ('UNCATEGORIZED', 'Uncategorized')], default='UNCATEGORIZED', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_usages', to='agent.activitysession')),
            ],
            options={
                'db_table': 'agent_app_usage',
            },
        ),
        migrations.CreateModel(
            name='IdleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('response', models.CharField(choices=[('WORKING', 'Was Working'), ('BREAK', 'Took a Break'), ('NO_RESPONSE', 'No Response')], default='NO_RESPONSE', max_length=20)),
                ('work_description', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idle_events', to='agent.activitysession')),
            ],
            options={
                'db_table': 'agent_idle_events',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(max_length=500)),
                ('captured_at', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='agent.activitysession')),
            ],
            options={
                'db_table': 'agent_screenshots',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('total_seconds', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('PRODUCTIVE', 'Productive'), ('NEUTRAL', 'Neutral'), ('UNPRODUCTIVE', 'Unproductive'), ('UNCATEGORIZED', 'Uncategorized')], default='UNCATEGORIZED', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_visits', to='agent.activitysession')),
            ],
            options={
                'db_table': 'agent_website_visits',
            },
        ),
    ]
