# Generated by Django 5.1.15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('employees', '0002_employee_address_employee_avatar_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivitySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('total_seconds', models.PositiveIntegerField(default=0)),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('idle_seconds', models.PositiveIntegerField(default=0)),
                ('productive_seconds', models.PositiveIntegerField(default=0)),
                ('unproductive_seconds', models.PositiveIntegerField(default=0)),
                ('neutral_seconds', models.PositiveIntegerField(default=0)),
                ('keystroke_count', models.PositiveIntegerField(default=0)),
                ('mouse_click_count', models.PositiveIntegerField(default=0)),
                ('screenshot_count', models.PositiveIntegerField(default=0)),
                ('idle_event_count', models.PositiveIntegerField(default=0)),
                ('productivity_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('top_apps', models.JSONField(default=list)),
                ('top_websites', models.JSONField(default=list)),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_summaries', to='employees.employee')),
            ],
            options={
                'db_table': 'agent_daily_summaries',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
