# Generated by Django 5.1.15 on 2026-03-16 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_address_employee_avatar_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('PEER', 'Peer'), ('MANAGER', 'Manager'), ('ANONYMOUS', 'Anonymous')], max_length=20)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('from_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to='employees.employee')),
                ('to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['from_employee'], name='idx_feedback_from'), models.Index(fields=['to_employee'], name='idx_feedback_to'), models.Index(fields=['type'], name='idx_feedback_type')],
            },
        ),
    ]
