"use client"

import * as React from "react"
import { useAuth } from "@/context/AuthContext"
import { useRouter } from "next/navigation"
import { api } from "@/lib/api-client"
import { motion, AnimatePresence } from "framer-motion"
import { PersonIcon, HomeIcon, LockClosedIcon, BackpackIcon, ReaderIcon, CheckIcon, ChevronLeftIcon, ChevronRightIcon, PlusIcon, TrashIcon, UploadIcon } from "@radix-ui/react-icons"

interface Education { degree: string; institution: string; field_of_study: string; start_year: string; end_year: string; grade: string }
const EMPTY_EDU: Education = { degree: "", institution: "", field_of_study: "", start_year: "", end_year: "", grade: "" }
const STEPS = [
    { key: "personal", label: "Personal Details", icon: PersonIcon },
    { key: "address", label: "Contact & Address", icon: HomeIcon },
    { key: "kyc", label: "KYC & Banking", icon: LockClosedIcon },
    { key: "education", label: "Education", icon: BackpackIcon },
    { key: "documents", label: "Documents", icon: ReaderIcon },
]

function Field({ label, children }: { label: string; children: React.ReactNode }) { return (<div className="space-y-1.5"><label className="text-xs font-semibold text-text-3 uppercase tracking-wider">{label}</label>{children}</div>) }
function Inp(props: React.InputHTMLAttributes<HTMLInputElement>) { return (<input {...props} className="w-full bg-surface border border-border rounded-lg px-3.5 py-2.5 text-sm text-text placeholder:text-text-4 focus:outline-none focus:border-accent focus:ring-2 focus:ring-accent/15 transition-all" />) }
function Sel({ children, ...props }: React.SelectHTMLAttributes<HTMLSelectElement> & { children: React.ReactNode }) { return (<select {...props} className="w-full bg-surface border border-border rounded-lg px-3.5 py-2.5 text-sm text-text focus:outline-none focus:border-accent focus:ring-2 focus:ring-accent/15 transition-all">{children}</select>) }

export default function OnboardingPage() {
    const { user, isLoading } = useAuth(); const router = useRouter()
    const [step, setStep] = React.useState(0)
    const [data, setData] = React.useState<Record<string, unknown>>({
        phone:"",date_of_birth:"",gender:"",blood_group:"",nationality:"Indian",marital_status:"",father_name:"",mother_name:"",spouse_name:"",
        emergency_contact_name:"",emergency_contact_phone:"",emergency_contact_relation:"",
        contact_address:"",contact_city:"",contact_state:"",contact_pincode:"",
        permanent_address:"",permanent_city:"",permanent_state:"",permanent_pincode:"",
        aadhaar_number:"",pan_number:"",passport_number:"",
        bank_name:"",bank_account_number:"",bank_branch:"",ifsc_code:"",pf_account_number:"",
        educations:[{...EMPTY_EDU}],
    })
    const [loading,setLoading]=React.useState(true); const [submitting,setSubmitting]=React.useState(false)
    const [error,setError]=React.useState(""); const [done,setDone]=React.useState(false)
    const [uploadedDocs,setUploadedDocs]=React.useState<{name:string;category:string}[]>([])
    const fileRef=React.useRef<HTMLInputElement>(null); const [docCat,setDocCat]=React.useState("ID_PROOF")

    React.useEffect(()=>{if(!isLoading&&user){if(user.isTenantAdmin||user.onboardingStatus==="completed")router.replace("/");if(user.mustChangePassword)router.replace("/change-password")}},[user,isLoading,router])

    React.useEffect(()=>{
        async function load(){
            try{
                const{data:p}=await api.get<Record<string,unknown>>("/employees/onboarding/")
                if(p){const m:Record<string,string>={phone:"phone",dateOfBirth:"date_of_birth",gender:"gender",bloodGroup:"blood_group",nationality:"nationality",maritalStatus:"marital_status",fatherName:"father_name",emergencyContactName:"emergency_contact_name",emergencyContactPhone:"emergency_contact_phone",emergencyContactRelation:"emergency_contact_relation",contactAddress:"contact_address",contactCity:"contact_city",contactState:"contact_state",contactPincode:"contact_pincode",permanentAddress:"permanent_address",permanentCity:"permanent_city",permanentState:"permanent_state",permanentPincode:"permanent_pincode",aadhaarNumber:"aadhaar_number",panNumber:"pan_number",passportNumber:"passport_number",bankName:"bank_name",bankAccountNumber:"bank_account_number",bankBranch:"bank_branch",ifscCode:"ifsc_code",pfAccountNumber:"pf_account_number"};setData(prev=>{const n={...prev};for(const[ck,sk]of Object.entries(m)){if(p[ck])n[sk]=p[ck] as string}return n})}
            }catch{}finally{setLoading(false)}
        }
        if(user&&!user.isTenantAdmin)load();else setLoading(false)
    },[user])

    const set=(f:string,v:string)=>setData(p=>({...p,[f]:v}))
    const edus=data.educations as Education[]
    const setEdu=(i:number,f:keyof Education,v:string)=>setData(p=>{const e=[...(p.educations as Education[])];e[i]={...e[i],[f]:v};return{...p,educations:e}})
    const addEdu=()=>setData(p=>({...p,educations:[...(p.educations as Education[]),{...EMPTY_EDU}]}))
    const rmEdu=(i:number)=>setData(p=>({...p,educations:(p.educations as Education[]).filter((_,j)=>j!==i)}))

    const handleDocUpload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;const fd=new FormData();fd.append("file",file);fd.append("title",file.name);fd.append("category",docCat);try{await api.upload("/documents/my/",fd);setUploadedDocs(p=>[...p,{name:file.name,category:docCat}])}catch{setError("Doc upload failed. Upload later from profile.")}if(fileRef.current)fileRef.current.value=""}
    const handleSubmit=async()=>{setError("");setSubmitting(true);try{await api.post("/employees/onboarding/",data);setDone(true);setTimeout(()=>{window.location.href="/"},2500)}catch(err:unknown){setError(String((err as Record<string,unknown>)?.message||"Failed to submit."))}finally{setSubmitting(false)}}

    if(isLoading||loading)return(<div className="min-h-screen flex items-center justify-center bg-bg"><div className="animate-spin w-8 h-8 border-2 border-accent border-t-transparent rounded-full"/></div>)
    if(done)return(<div className="min-h-screen flex items-center justify-center bg-bg"><motion.div initial={{scale:0.9,opacity:0}} animate={{scale:1,opacity:1}} className="text-center space-y-4"><div className="w-16 h-16 rounded-full bg-success/20 border-2 border-success/40 flex items-center justify-center mx-auto"><CheckIcon className="w-8 h-8 text-success"/></div><h2 className="text-xl font-bold text-text">Onboarding Complete!</h2><p className="text-sm text-text-3">Redirecting to dashboard...</p></motion.div></div>)

    const canNext=()=>{switch(step){case 0:return!!data.phone&&!!data.date_of_birth&&!!data.gender;case 1:return!!data.contact_address&&!!data.contact_city&&!!data.contact_state;default:return true}}
    const isLast=step===STEPS.length-1
    const firstName=user?.name?.split(" ")[0]||""
    return(
        <div className="min-h-screen bg-bg">
            <div className="bg-surface border-b border-border"><div className="max-w-3xl mx-auto px-6 py-5"><h1 className="text-xl font-bold text-text">{firstName?`Welcome, ${firstName}!`:"Welcome!"}</h1><p className="text-sm text-text-3 mt-1">Complete your profile to get started (~5 min).</p></div></div>
            <div className="max-w-3xl mx-auto px-6 py-4"><div className="flex items-center gap-1">{STEPS.map((s,i)=>{const Icon=s.icon;const a=i===step;const p=i<step;return(<React.Fragment key={s.key}><button onClick={()=>i<=step&&setStep(i)} disabled={i>step} className={`flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-semibold transition-all ${a?"bg-accent/10 text-accent border border-accent/30":p?"bg-success/10 text-success cursor-pointer":"text-text-4 cursor-default"}`}>{p?<CheckIcon className="w-3.5 h-3.5"/>:<Icon className="w-3.5 h-3.5"/>}<span className="hidden sm:inline">{s.label}</span></button>{i<STEPS.length-1&&<div className={`flex-1 h-px ${i<step?"bg-success/40":"bg-border"}`}/>}</React.Fragment>)})}</div></div>
            <div className="max-w-3xl mx-auto px-6 pb-32"><AnimatePresence mode="wait"><motion.div key={step} initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-20}} transition={{duration:0.2}} className="bg-surface border border-border rounded-2xl p-6 space-y-5"><h2 className="text-lg font-bold text-text">{STEPS[step].label}</h2>
                {step===0&&(<div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Field label="Phone *"><Inp value={data.phone as string} onChange={e=>set("phone",e.target.value)} placeholder="e.g. 9876543210"/></Field><Field label="Date of Birth *"><Inp type="date" value={data.date_of_birth as string} onChange={e=>set("date_of_birth",e.target.value)}/></Field><Field label="Gender *"><Sel value={data.gender as string} onChange={e=>set("gender",e.target.value)}><option value="">Select...</option><option value="Male">Male</option><option value="Female">Female</option><option value="Other">Other</option></Sel></Field><Field label="Blood Group"><Sel value={data.blood_group as string} onChange={e=>set("blood_group",e.target.value)}><option value="">Select...</option>{["A+","A-","B+","B-","AB+","AB-","O+","O-"].map(g=><option key={g} value={g}>{g}</option>)}</Sel></Field><Field label="Nationality"><Inp value={data.nationality as string} onChange={e=>set("nationality",e.target.value)}/></Field><Field label="Marital Status"><Sel value={data.marital_status as string} onChange={e=>set("marital_status",e.target.value)}><option value="">Select...</option><option value="Single">Single</option><option value="Married">Married</option></Sel></Field><Field label="Father Name"><Inp value={data.father_name as string} onChange={e=>set("father_name",e.target.value)}/></Field><Field label="Mother Name"><Inp value={data.mother_name as string} onChange={e=>set("mother_name",e.target.value)}/></Field><Field label="Spouse Name"><Inp value={data.spouse_name as string} onChange={e=>set("spouse_name",e.target.value)} placeholder="If applicable"/></Field><div className="sm:col-span-2 pt-2 border-t border-border"><p className="text-xs font-semibold text-text-3 uppercase tracking-wider mb-3">Emergency Contact</p><div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><Field label="Name *"><Inp value={data.emergency_contact_name as string} onChange={e=>set("emergency_contact_name",e.target.value)}/></Field><Field label="Phone *"><Inp value={data.emergency_contact_phone as string} onChange={e=>set("emergency_contact_phone",e.target.value)}/></Field><Field label="Relation"><Inp value={data.emergency_contact_relation as string} onChange={e=>set("emergency_contact_relation",e.target.value)} placeholder="e.g. Father"/></Field></div></div></div>)}
                {step===1&&(<div className="space-y-6"><div><p className="text-sm font-semibold text-text mb-3">Current Address</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="sm:col-span-2"><Field label="Address *"><Inp value={data.contact_address as string} onChange={e=>set("contact_address",e.target.value)} placeholder="Street, Area"/></Field></div><Field label="City *"><Inp value={data.contact_city as string} onChange={e=>set("contact_city",e.target.value)}/></Field><Field label="State *"><Inp value={data.contact_state as string} onChange={e=>set("contact_state",e.target.value)}/></Field><Field label="Pin Code"><Inp value={data.contact_pincode as string} onChange={e=>set("contact_pincode",e.target.value)}/></Field></div></div><div className="border-t border-border pt-4"><div className="flex items-center justify-between mb-3"><p className="text-sm font-semibold text-text">Permanent Address</p><button type="button" className="text-xs text-accent hover:underline" onClick={()=>{set("permanent_address",data.contact_address as string);set("permanent_city",data.contact_city as string);set("permanent_state",data.contact_state as string);set("permanent_pincode",data.contact_pincode as string)}}>Same as current</button></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="sm:col-span-2"><Field label="Address"><Inp value={data.permanent_address as string} onChange={e=>set("permanent_address",e.target.value)}/></Field></div><Field label="City"><Inp value={data.permanent_city as string} onChange={e=>set("permanent_city",e.target.value)}/></Field><Field label="State"><Inp value={data.permanent_state as string} onChange={e=>set("permanent_state",e.target.value)}/></Field><Field label="Pin Code"><Inp value={data.permanent_pincode as string} onChange={e=>set("permanent_pincode",e.target.value)}/></Field></div></div></div>)}
                {step===2&&(<div className="space-y-6"><div><p className="text-sm font-semibold text-text mb-3">Identity Documents</p><div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><Field label="Aadhaar"><Inp value={data.aadhaar_number as string} onChange={e=>set("aadhaar_number",e.target.value)} maxLength={12} placeholder="12-digit"/></Field><Field label="PAN"><Inp value={data.pan_number as string} onChange={e=>set("pan_number",e.target.value.toUpperCase())} maxLength={10} placeholder="ABCDE1234F"/></Field><Field label="Passport"><Inp value={data.passport_number as string} onChange={e=>set("passport_number",e.target.value)} placeholder="If available"/></Field></div></div><div className="border-t border-border pt-4"><p className="text-sm font-semibold text-text mb-3">Bank Details</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Field label="Bank Name"><Inp value={data.bank_name as string} onChange={e=>set("bank_name",e.target.value)}/></Field><Field label="Account Number"><Inp value={data.bank_account_number as string} onChange={e=>set("bank_account_number",e.target.value)}/></Field><Field label="Branch"><Inp value={data.bank_branch as string} onChange={e=>set("bank_branch",e.target.value)}/></Field><Field label="IFSC"><Inp value={data.ifsc_code as string} onChange={e=>set("ifsc_code",e.target.value.toUpperCase())} placeholder="SBIN0001234"/></Field><Field label="PF Account"><Inp value={data.pf_account_number as string} onChange={e=>set("pf_account_number",e.target.value)} placeholder="If available"/></Field></div></div></div>)}
                {step===3&&(<div className="space-y-4">{edus.map((edu,idx)=>(<div key={idx} className="border border-border rounded-xl p-4 space-y-3"><div className="flex items-center justify-between"><span className="text-sm font-semibold text-text">Education {idx+1}</span>{edus.length>1&&<button onClick={()=>rmEdu(idx)} className="text-danger hover:text-danger/80 p-1"><TrashIcon className="w-4 h-4"/></button>}</div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><Field label="Degree"><Inp value={edu.degree} onChange={e=>setEdu(idx,"degree",e.target.value)} placeholder="e.g. B.Tech"/></Field><Field label="Institution"><Inp value={edu.institution} onChange={e=>setEdu(idx,"institution",e.target.value)}/></Field><Field label="Field"><Inp value={edu.field_of_study} onChange={e=>setEdu(idx,"field_of_study",e.target.value)}/></Field><Field label="Grade"><Inp value={edu.grade} onChange={e=>setEdu(idx,"grade",e.target.value)}/></Field><Field label="Start Year"><Inp type="number" value={edu.start_year} onChange={e=>setEdu(idx,"start_year",e.target.value)} min="1970" max="2030"/></Field><Field label="End Year"><Inp type="number" value={edu.end_year} onChange={e=>setEdu(idx,"end_year",e.target.value)} min="1970" max="2030"/></Field></div></div>))}<button onClick={addEdu} className="flex items-center gap-2 text-sm text-accent hover:text-accent/80 font-medium"><PlusIcon className="w-4 h-4"/> Add education</button></div>)}
                {step===4&&(<div className="space-y-4"><p className="text-sm text-text-3">Upload KYC docs, certificates, etc. You can also do this later from your profile.</p><div className="flex items-end gap-3"><div className="flex-1"><Field label="Category"><Sel value={docCat} onChange={e=>setDocCat(e.target.value)}><option value="ID_PROOF">ID Proof</option><option value="CERTIFICATE">Certificate</option><option value="CONTRACT">Contract</option><option value="OTHER">Other</option></Sel></Field></div><button onClick={()=>fileRef.current?.click()} className="flex items-center gap-2 px-4 py-2.5 bg-accent text-white rounded-lg text-sm font-semibold hover:bg-accent/90 transition-colors"><UploadIcon className="w-4 h-4"/> Upload</button><input ref={fileRef} type="file" className="hidden" onChange={handleDocUpload} accept=".pdf,.jpg,.jpeg,.png,.doc,.docx"/></div>{uploadedDocs.length>0&&(<div className="space-y-2"><p className="text-xs font-semibold text-text-3 uppercase">Uploaded</p>{uploadedDocs.map((d,i)=>(<div key={i} className="flex items-center gap-3 bg-bg-2 rounded-lg px-3 py-2 text-sm"><CheckIcon className="w-4 h-4 text-success"/><span className="text-text flex-1 truncate">{d.name}</span><span className="text-xs text-text-4">{d.category}</span></div>))}</div>)}</div>)}
            </motion.div></AnimatePresence>{error&&<div className="mt-4 bg-danger/10 border border-danger/20 rounded-lg px-4 py-3 text-sm text-danger">{error}</div>}</div>
            <div className="fixed bottom-0 left-0 right-0 bg-surface border-t border-border"><div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between"><button onClick={()=>setStep(s=>s-1)} disabled={step===0} className="flex items-center gap-2 px-4 py-2.5 text-sm font-medium text-text-3 hover:text-text disabled:opacity-30 disabled:cursor-not-allowed transition-colors"><ChevronLeftIcon className="w-4 h-4"/> Back</button><span className="text-xs text-text-4">Step {step+1} of {STEPS.length}</span>{isLast?<button onClick={handleSubmit} disabled={submitting} className="flex items-center gap-2 px-6 py-2.5 bg-success text-white rounded-lg text-sm font-semibold hover:bg-success/90 disabled:opacity-50 transition-colors">{submitting?"Submitting...":"Complete Onboarding"} <CheckIcon className="w-4 h-4"/></button>:<button onClick={()=>setStep(s=>s+1)} disabled={!canNext()} className="flex items-center gap-2 px-6 py-2.5 bg-accent text-white rounded-lg text-sm font-semibold hover:bg-accent/90 disabled:opacity-50 transition-colors">Next <ChevronRightIcon className="w-4 h-4"/></button>}</div></div>
        </div>)
}
