# Generated by Django 5.1.15 on 2026-03-16 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_address_employee_avatar_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_all_day', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('MEETING', 'Meeting'), ('HOLIDAY', 'Holiday'), ('BIRTHDAY', 'Birthday'), ('COMPANY', 'Company Event'), ('TRAINING', 'Training')], default='MEETING', max_length=20)),
                ('attendees', models.ManyToManyField(blank=True, related_name='events', to='employees.employee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to='employees.employee')),
            ],
            options={
                'db_table': 'calendar_events',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='idx_event_dates'), models.Index(fields=['type'], name='idx_event_type'), models.Index(fields=['created_by'], name='idx_event_created_by')],
            },
        ),
    ]
