# Generated by Django 5.1.15 on 2026-03-16 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_address_employee_avatar_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'functional_roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeFunctionalRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functional_roles', to='employees.employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='roles.functionalrole')),
            ],
            options={
                'db_table': 'employee_functional_roles',
                'unique_together': {('employee', 'role')},
            },
        ),
        migrations.CreateModel(
            name='RoleCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.CharField(max_length=100)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='roles.functionalrole')),
            ],
            options={
                'db_table': 'role_capabilities',
                'unique_together': {('role', 'capability')},
            },
        ),
    ]
