# Generated by Django 5.1.15 on 2026-03-17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        # ── Attendance ────────────────────────────────────────────────
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('work_hours', models.FloatField(blank=True, null=True)),
                ('overtime', models.FloatField(default=0, help_text='Overtime in minutes')),
                ('is_late', models.BooleanField(default=False)),
                ('is_early_exit', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('ON_LEAVE', 'On Leave'), ('WEEKEND', 'Weekend')], default='PRESENT', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
            ],
            options={
                'db_table': 'attendances',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'date'], name='attendance_employe_date_idx'),
        ),

        # ── Shift ─────────────────────────────────────────────────────
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('work_days', models.JSONField(default=list, help_text='List of integers 0-6 (Mon=0, Sun=6)')),
            ],
            options={
                'db_table': 'shifts',
                'ordering': ['name'],
            },
        ),

        # ── Time Session ──────────────────────────────────────────────
        migrations.CreateModel(
            name='TimeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('total_work', models.IntegerField(default=0, help_text='Total work in seconds')),
                ('total_break', models.IntegerField(default=0, help_text='Total break in seconds')),
                ('total_idle', models.IntegerField(default=0, help_text='Total idle in seconds')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BREAK', 'Break'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_sessions', to='employees.employee')),
            ],
            options={
                'db_table': 'time_sessions',
                'ordering': ['-created_at'],
            },
        ),

        # ── Break Entry ───────────────────────────────────────────────
        migrations.CreateModel(
            name='BreakEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='attendance.timesession')),
            ],
            options={
                'db_table': 'break_entries',
            },
        ),

        # ── Shift Assignment ─────────────────────────────────────────
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='employees.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='attendance.shift')),
            ],
            options={
                'db_table': 'shift_assignments',
            },
        ),

        # ── Attendance Policy ─────────────────────────────────────────
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='DEFAULT', max_length=100)),
                ('late_grace_period', models.IntegerField(default=15, help_text='Late grace period in minutes')),
                ('early_exit_grace', models.IntegerField(default=15, help_text='Early exit grace period in minutes')),
                ('ot_threshold', models.IntegerField(default=60, help_text='Overtime threshold in minutes')),
            ],
            options={
                'db_table': 'attendance_policies',
            },
        ),

        # ── Holiday ───────────────────────────────────────────────────
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('is_optional', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'holidays',
                'ordering': ['date'],
            },
        ),

        # ── Attendance Regularization ─────────────────────────────────
        migrations.CreateModel(
            name='AttendanceRegularization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('requested_time', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('MISSING_PUNCH', 'Missing Punch'), ('LATE_CORRECTION', 'Late Correction'), ('EARLY_EXIT_CORRECTION', 'Early Exit Correction')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regularization', to='attendance.attendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularizations', to='employees.employee')),
            ],
            options={
                'db_table': 'attendance_regularizations',
            },
        ),
    ]
