# Generated by Django 5.1.15 on 2026-03-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendance',
            new_name='attendances_employe_993bac_idx',
            old_name='attendance_employe_date_idx',
        ),
    ]
