# Generated by Django 5.1.15 on 2026-03-16 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_address_employee_avatar_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('criteria', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'performance_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=50)),
                ('task_completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('attendance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('collaboration_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quality_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perf_metrics', to='employees.employee')),
            ],
            options={
                'db_table': 'performance_metrics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=50)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('strengths', models.TextField(blank=True)),
                ('improvements', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ACKNOWLEDGED', 'Acknowledged')], default='DRAFT', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='employees.employee')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to='employees.employee')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.performancetemplate')),
            ],
            options={
                'db_table': 'performance_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
