# Generated by Django 5.1.15 on 2026-03-21 08:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_address_employee_avatar_url_and_more'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('SIX_MONTHLY', 'Six-Monthly'), ('ANNUAL', 'Annual')], max_length=20)),
                ('period_label', models.CharField(max_length=100)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('financial_year', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='OPEN', max_length=20)),
            ],
            options={
                'db_table': 'review_cycles',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_type', models.CharField(choices=[('ANNUAL', 'Annual'), ('SIX_MONTHLY', 'Six-Monthly (Exceptional Performer)')], max_length=20)),
                ('review_period', models.CharField(max_length=100)),
                ('financial_year', models.CharField(max_length=10)),
                ('monthly_summary', models.JSONField(default=list)),
                ('conversion_kpis', models.JSONField(default=list)),
                ('recruiter_competencies', models.JSONField(default=list)),
                ('team_lead_competencies', models.JSONField(blank=True, default=list)),
                ('self_assessment', models.JSONField(default=dict)),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('final_rating_category', models.CharField(blank=True, choices=[('OUTSTANDING', 'Outstanding (90–100%)'), ('EXCELLENT', 'Excellent (75–89%)'), ('GOOD', 'Good (60–74%)'), ('NEEDS_IMPROVEMENT', 'Needs Improvement (40–59%)'), ('UNSATISFACTORY', 'Unsatisfactory (Below 40%)')], max_length=30)),
                ('key_strengths', models.TextField(blank=True)),
                ('development_areas', models.TextField(blank=True)),
                ('goals_next_period', models.TextField(blank=True)),
                ('training_recommended', models.TextField(blank=True)),
                ('promotion_recommendation', models.TextField(blank=True)),
                ('salary_revision_recommendation', models.TextField(blank=True)),
                ('outcome_decision', models.CharField(blank=True, choices=[('PROMOTION', 'Promotion + Salary Revision'), ('SALARY_REVISION', 'Salary Revision'), ('STANDARD_INCREMENT', 'Standard Increment'), ('PIP_60', '60-Day PIP'), ('PIP_90', '90-Day PIP + Warning')], max_length=30)),
                ('additional_hr_remarks', models.TextField(blank=True)),
                ('employee_signed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_signed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_signed_at', models.DateTimeField(blank=True, null=True)),
                ('is_eligible', models.BooleanField(default=False)),
                ('eligibility_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DATA_COMPILATION', 'Data Compilation'), ('SELF_ASSESSMENT', 'Self-Assessment'), ('MANAGER_REVIEW', 'Manager Review'), ('HR_CALIBRATION', 'HR Calibration'), ('ONE_ON_ONE', 'One-on-One Meeting'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='employees.employee')),
                ('hr_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisals_reviewed', to='employees.employee')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisals_managed', to='employees.employee')),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisals', to='performance.reviewcycle')),
            ],
            options={
                'db_table': 'appraisals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_month', models.PositiveSmallIntegerField()),
                ('review_year', models.PositiveIntegerField()),
                ('recruiter_metrics', models.JSONField(default=list)),
                ('team_lead_metrics', models.JSONField(blank=True, default=list)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating_category', models.CharField(blank=True, choices=[('OUTSTANDING', 'Outstanding (90–100%)'), ('EXCELLENT', 'Excellent (75–89%)'), ('GOOD', 'Good (60–74%)'), ('NEEDS_IMPROVEMENT', 'Needs Improvement (40–59%)'), ('UNSATISFACTORY', 'Unsatisfactory (Below 40%)')], max_length=30)),
                ('score_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reviewer_remarks', models.TextField(blank=True)),
                ('strengths_observed', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('action_items', models.TextField(blank=True)),
                ('appreciation_or_alert', models.CharField(blank=True, choices=[('APPRECIATION', 'Appreciation (Rating 4–5)'), ('SATISFACTORY', 'Satisfactory (Rating 3)'), ('ALERT', 'Performance Alert (Rating 1–2)')], max_length=20)),
                ('employee_signed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_signed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_signed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SELF_ASSESSMENT', 'Self-Assessment Submitted'), ('SUBMITTED', 'Submitted to HR'), ('REVIEWED', 'HR Reviewed'), ('ACKNOWLEDGED', 'Employee Acknowledged')], default='DRAFT', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reviews', to='employees.employee')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_reviews_managed', to='employees.employee')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_reviews_given', to='employees.employee')),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_reviews', to='performance.reviewcycle')),
            ],
            options={
                'db_table': 'monthly_reviews',
                'ordering': ['-review_year', '-review_month'],
                'unique_together': {('employee', 'review_month', 'review_year')},
            },
        ),
        migrations.CreateModel(
            name='PIP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pip_type', models.CharField(choices=[('MONTHLY_30', '30-Day (Monthly Alert)'), ('FORMAL_60', '60-Day (Appraisal Rating 2)'), ('FORMAL_90', '90-Day (Appraisal Rating 1)')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('specific_targets', models.JSONField(default=list)),
                ('weekly_checkins', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('EXTENDED', 'Extended'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('outcome', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pips', to='employees.employee')),
                ('triggered_by_appraisal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pips', to='performance.appraisal')),
                ('triggered_by_monthly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pips', to='performance.monthlyreview')),
            ],
            options={
                'db_table': 'performance_pips',
                'ordering': ['-start_date'],
            },
        ),
    ]
