# Generated by Django 5.1.15 on 2026-03-17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        # ── Payroll ───────────────────────────────────────────────────
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.CharField(max_length=7)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('arrears', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reimbursements', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pf_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loans_advances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('is_finalized', models.BooleanField(default=False)),
                ('pdf_url', models.URLField(blank=True, max_length=500, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employees.employee')),
            ],
            options={
                'db_table': 'payrolls',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'month')},
            },
        ),

        # ── Provident Fund ────────────────────────────────────────────
        migrations.CreateModel(
            name='ProvidentFund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.CharField(max_length=7)),
                ('account_number', models.CharField(max_length=50)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee_contribution', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employer_contribution', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_contribution', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='Credited', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_records', to='employees.employee')),
            ],
            options={
                'db_table': 'provident_funds',
                'ordering': ['-created_at'],
            },
        ),

        # ── Compliance Configuration ──────────────────────────────────
        migrations.CreateModel(
            name='PayrollComplianceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regime_name', models.CharField(default='DEFAULT', max_length=100)),
                ('pf_percentage', models.FloatField(default=12.0)),
                ('standard_deduction', models.FloatField(default=50000.0)),
                ('health_cess', models.FloatField(default=4.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'payroll_compliance_configs',
            },
        ),

        # ── Tax Slabs ─────────────────────────────────────────────────
        migrations.CreateModel(
            name='TaxSlab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_income', models.FloatField()),
                ('max_income', models.FloatField(blank=True, null=True)),
                ('tax_rate', models.FloatField()),
                ('base_tax', models.FloatField(default=0)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_slabs', to='payroll.payrollcomplianceconfig')),
            ],
            options={
                'db_table': 'tax_slabs',
                'ordering': ['min_income'],
            },
        ),

        # ── Payroll Audit Trail ───────────────────────────────────────
        migrations.CreateModel(
            name='PayrollAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('RUN_CALCULATION', 'Run Calculation'), ('MANUAL_OVERRIDE', 'Manual Override'), ('FINALIZED', 'Finalized'), ('LOCKED', 'Locked')], max_length=30)),
                ('actor_id', models.UUIDField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='payroll.payroll')),
            ],
            options={
                'db_table': 'payroll_audits',
                'ordering': ['-created_at'],
            },
        ),
    ]
