# Generated by Django 5.1.15 on 2026-03-16 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='employees.employee')),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Kudos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('TEAMWORK', 'Teamwork'), ('INNOVATION', 'Innovation'), ('LEADERSHIP', 'Leadership'), ('HELPING', 'Helping Hand'), ('EXCELLENCE', 'Excellence')], default='TEAMWORK', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('from_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kudos_given', to='employees.employee')),
                ('to_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kudos_received', to='employees.employee')),
            ],
            options={
                'db_table': 'kudos',
                'ordering': ['-created_at'],
            },
        ),
    ]
