# Generated by Django 5.1.15 on 2026-03-17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('CASUAL', 'Casual'), ('SICK', 'Sick'), ('EARNED', 'Earned'), ('MATERNITY', 'Maternity'), ('PATERNITY', 'Paternity'), ('UNPAID', 'Unpaid')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='employees.employee')),
            ],
            options={
                'db_table': 'leaves',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['employee'], name='idx_leave_employee'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['status'], name='idx_leave_status'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['employee', 'start_date', 'end_date'], name='idx_leave_emp_dates'),
        ),
    ]
