# Generated by Django 5.1.15 on 2026-03-16 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '__first__'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='department_ref',
            field=models.ForeignKey(blank=True, db_column='department_ref_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='departments.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('pre_joining', 'Pre Joining'), ('active', 'Active'), ('on_notice', 'On Notice'), ('on_leave', 'On Leave'), ('resigned', 'Resigned'), ('terminated', 'Terminated'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('exited', 'Exited')], default='pre_joining', max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_address', models.TextField(blank=True)),
                ('contact_city', models.CharField(blank=True, max_length=100)),
                ('contact_state', models.CharField(blank=True, max_length=100)),
                ('contact_pincode', models.CharField(blank=True, max_length=20)),
                ('contact_country', models.CharField(blank=True, default='India', max_length=100)),
                ('permanent_address', models.TextField(blank=True)),
                ('permanent_city', models.CharField(blank=True, max_length=100)),
                ('permanent_state', models.CharField(blank=True, max_length=100)),
                ('permanent_pincode', models.CharField(blank=True, max_length=20)),
                ('permanent_country', models.CharField(blank=True, default='India', max_length=100)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_info', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_addresses',
            },
        ),
        migrations.CreateModel(
            name='EmployeeBanking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_branch', models.CharField(blank=True, max_length=200)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('pf_account_number', models.CharField(blank=True, max_length=50)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banking', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_banking',
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('marital_status', models.CharField(blank=True, max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('caste', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('spouse_name', models.CharField(blank=True, max_length=100)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('visa_type', models.CharField(blank=True, max_length=50)),
                ('visa_expiry', models.DateField(blank=True, null=True)),
                ('previous_company', models.CharField(blank=True, max_length=200)),
                ('previous_designation', models.CharField(blank=True, max_length=200)),
                ('previous_experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('total_experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_profiles',
            },
        ),
    ]
