# Generated by Django 5.1.15 on 2026-03-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_add_onboarding_status_and_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='previous_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
