# Generated by Django 5.1.15 on 2026-03-17
# Dashboard app uses aggregation queries — no dedicated models needed.

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = []
