# Generated by Django 5.1.15 on 2026-03-25 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_address_employee_avatar_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('entity_type', models.CharField(choices=[('LEAVE', 'Leave Request'), ('REIMBURSEMENT', 'Reimbursement'), ('RESIGNATION', 'Resignation'), ('ASSET_REQUEST', 'Asset Request'), ('ONBOARDING', 'Onboarding'), ('OFFBOARDING', 'Offboarding')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to='employees.employee')),
            ],
            options={
                'db_table': 'workflow_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('approver_type', models.CharField(choices=[('REPORTING_MANAGER', 'Reporting Manager'), ('HR', 'HR'), ('DEPARTMENT_HEAD', 'Department Head'), ('SPECIFIC_EMPLOYEE', 'Specific Employee'), ('AUTO_APPROVE', 'Auto Approve')], max_length=30)),
                ('sla_hours', models.PositiveIntegerField(default=24, help_text='SLA in hours')),
                ('is_optional', models.BooleanField(default=False)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_approver_steps', to='employees.employee')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflowtemplate')),
            ],
            options={
                'db_table': 'workflow_steps',
                'ordering': ['order'],
            },
        ),
    ]
